- link:
    ~/.dir_colors: etc/dir_colors
    ~/.editorconfig: etc/editorconfig
    ~/.pythonrc: etc/pythonrc
    ~/.slate: etc/slate
    ~/.tmux.conf: etc/tmux.conf
    ~/.valgrindrc: etc/valgrindrc
    ~/.wgetrc: etc/wgetrc
    ~/.htoprc: etc/htoprc
    ~/.hammerspoon: hammerspoon
    ~/bin: bin

