- link:
    ~/.vimrc:                etc/vim/vimrc
    ~/.gvimrc:               etc/vim/gvimrc
    ~/.vim:                  etc/vim
    ~/.config/nvim/init.vim: etc/vim/vimrc

- shell:
    - [vim -c 'PlugInstall' +qall, Installing vim plugins]

