- link:
    ~/.vimrc:                vim/vimrc
    ~/.gvimrc:               vim/gvimrc
    ~/.vim:                  vim
    ~/.config/nvim/init.vim: vim/vimrc

- shell:
    - [vim -c 'PlugInstall' +qall, Installing vim plugins]

