" {{{
" Maintainer: Johannes Steudle
" .gvimrc
"     for Unix and macOS: ~/.gvimrc
" }}}

" Font {{{
if has('gui_gtk2')
    set guifont=Inconsolata\ 13
elseif has('gui_macvim')
    set guifont=SF\ Mono\ Medium:h13
elseif has('gui_win32')
    set guifont=Consolas:h13:cANSI
endif
" }}}

" Configuration {{{
if &diff " setup for diff mode
    " set lines=999 columns=999
    " double the width up to a reasonable maximum
    winpos 0 23
    let &columns = ((&columns * 2 > 250) ? 250 : &columns * 2)
else " setup for non-diff mode
    set lines=70
    set columns=120
endif
set guioptions-=aA
set guioptions+=ci " no toolbar, menubar, scrollbar
set linespace=2
set mousehide      " Hide the mouse when typing text
" set mouse-=a " Disable mouse selection
" }}}

" Keyboard {{{
map! <S-Insert> <MiddleMouse> " Make shift-insert work like in Xterm
" }}}

" Spellchecking {{{
fun SetSpellCheck() abort
    set spell spelllang=en,de		    " Spell checking language
    set spell spellsuggest=double,10	" Description of the spell-checker
                                        " zg to add word to word list
                                        " zw to reverse
                                        " zug to remove word from word list
                                        " z= to get list of possibilities
endfun
" }}}

" ShowMarks {{{
let showmarks_include = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
" Don't leave on by default, use :ShowMarksOn to enable
let g:showmarks_enable = 1
" For marks a-z
highlight ShowMarksHLl gui=bold guibg=LightBlue guifg=Blue
" For marks A-Z
highlight ShowMarksHLu gui=bold guibg=LightRed guifg=DarkRed
" For all other marks
highlight ShowMarksHLo gui=bold guibg=LightYellow guifg=DarkYellow
" For multiple marks on the same line.
highlight ShowMarksHLm gui=bold guibg=LightGreen guifg=DarkGreen
" }}}
