# {{{
#
# Author: Johannes Steudle
# File: .zshrc
# Date: 17.03.2014
#
# Description: .zshrc general settings
#
# }}}

# export DEBUG_ZSH=true

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to zsh configuration directory
ZSH=$HOME/.zsh

# Set name of the theme to load.
# ZSH_THEME="tweetjay"
ZSH_THEME="powerlevel10k"

plugins=(hosts zsh-interactive-cd zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search)

# Set language environment
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LANG="en_GB.UTF-8"

source $ZSH/init_zsh.zsh

# Set default editor
export EDITOR=nvim
export PAGER=less

if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
