# {{{
#
# Author: Johannes Steudle
# File: .zshrc
#
# Description: .zshrc general settings
#
# }}}

# export DEBUG_ZSH=true

# Path to zsh configuration directory
ZSH=$HOME/.zsh

# Set language environment
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LANG="en_GB.UTF-8"

plugins=(hosts zsh-interactive-cd zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search zsh-z)

source $ZSH/init_zsh.zsh

test -e "$HOME/.shellfishrc" && source "$HOME/.shellfishrc"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Load Angular CLI autocompletion.
source <(ng completion script)
