tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"
tap "caskroom/fonts"

# iOS
brew "carthage"
brew "chisel"
brew "swiftlint"
brew "marathon-swift"
brew "xctool"
brew "ideviceinstaller"

# git
brew "git"
brew "git-extras"
brew "git-flow-avh"
brew "git-lfs"
brew "gist"
brew "tig"

# languages
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "python"
brew "ruby"
brew "erlang"
brew "haskell-stack"

# shells
brew "fish"

brew "bash"
brew "bash-completion@2"

brew "zsh"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# shell tools
brew "tmux"
brew "tree"
brew "wget", args: ["with-iri"]
brew "neovim"
brew "vim", args: ["with-override-system-vi"]
brew "ffmpeg"
brew "mas"
brew "fswatch"
brew "openssl"
brew "openssh"
brew "htop"
brew "iftop"
brew "icdiff"
brew "the_silver_searcher"
brew "z"
brew "cmake"
brew "nmap"
brew "cntlm"
brew "openconnect"
brew "curl"
brew "duti"
brew "exa" # cool ls -la
# brew "coreutils"
# brew "multitail"
# brew "exercism"

cask "alfred"
cask "macvim"
cask "hammerspoon"
# cask "little-snitch"
# cask "micro-snitch"
cask "iterm2"
cask "sublime-text"
cask "dash"
# cask "kdiff3"
cask "sourcetree"
cask "sketch"
cask "hopper-disassembler"
cask "uncrustifyx"
cask "quickradar"
cask "simsim"
cask "docker"
cask "arduino"
cask "fritzing"
cask "caffeine"
cask "vlc"
cask "wireshark"

# mas "1Password", id: 443987910
mas "Tweetbot", id: 557168941
mas "Fantastical 2", id: 975937182
mas "Xcode", id: 497799835
mas "Affinity Designer", id: 824171161
